export const GET_ALL_BLOGS_REQUEST = 'GET_ALL_BLOGS_REQUEST';
export const GET_ALL_BLOGS_SUCCESS = 'GET_ALL_BLOGS_SUCCESS';
export const GET_ALL_BLOGS_FAIL = 'GET_ALL_BLOGS_FAIL';
export const ADD_NEW_BLOG_TO_LIST = 'ADD_NEW_BLOG_TO_LIST';
export const DELETE_BLOG_FROM_LIST = 'DELETE_BLOG_FROM_LIST';
export const UPDATE_BLOG_IN_LIST = 'UPDATE_BLOG_IN_LIST';

export const GET_ONE_BLOG_REQUEST = 'GET_ONE_BLOG_REQUEST';
export const GET_ONE_BLOG_SUCCESS = 'GET_ONE_BLOG_SUCCESS';
export const GET_ONE_BLOG_FAIL = 'GET_ONE_BLOG_FAIL';

export const NEW_BLOG_REQUEST = 'NEW_BLOG_REQUEST';
export const NEW_BLOG_SUCCESS = 'NEW_BLOG_SUCCESS';
export const NEW_BLOG_FAIL = 'NEW_BLOG_FAIL';

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAIL = 'UPDATE_BLOG_FAIL';

export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL';

export const REFRESH_BLOG_STATE = 'REFRESH_BLOG_STATE';
